## Hands-on Task 2: Basic Machine Learning Experiment

In [1]:
import numpy as np
import pandas as pd
import torch
import sklearn

In [3]:
#load the iris dataset
from sklearn.datasets import load_iris

iris = load_iris()

x = iris.data
y = iris.target
print(x.shape, y.shape)

(150, 4) (150,)


In [5]:
#split the dataset into training and testing sets
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, 
    y, 
    test_size=0.2, 
    random_state=47
)

In [9]:
#evaluate the models
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [6]:
#create a logistic regression model
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression(max_iter=1000)
model1.fit(x_train, y_train)
y_train_pred = model1.predict(x_train)
y_test_pred = model1.predict(x_test)


In [12]:
#model 1 evaluation
train_acc1 = accuracy_score(y_train, y_train_pred)
test_acc1 = accuracy_score(y_test, y_test_pred)
cm1 = confusion_matrix(y_test, y_test_pred)
print("train_acc1: ", train_acc1)
print("test_acc1: ", test_acc1)
print(cm1)

train_acc1:  0.9583333333333334
test_acc1:  0.9666666666666667
[[11  0  0]
 [ 0  7  0]
 [ 0  1 11]]


In [7]:
#create a k-nearest neighbors model
from sklearn.neighbors import KNeighborsClassifier
model2 = KNeighborsClassifier(n_neighbors=3)
model2.fit(x_train, y_train)
y_train_pred_knn = model2.predict(x_train)
y_test_pred_knn = model2.predict(x_test)

In [16]:
#model 2 evaluation
train_acc2 = accuracy_score(y_train, y_train_pred_knn)
test_acc2 = accuracy_score(y_test, y_test_pred_knn)
cm2 = confusion_matrix(y_test, y_test_pred_knn)
print("train_acc2: ", train_acc2)
print("test_acc2: ", test_acc2)
print(cm2)

train_acc2:  0.9583333333333334
test_acc2:  0.9666666666666667
[[11  0  0]
 [ 0  7  0]
 [ 0  1 11]]


In [14]:
#create a decision tree model
from sklearn.tree import DecisionTreeClassifier
model3 = DecisionTreeClassifier()
model3.fit(x_train, y_train)
y_train_pred_tree = model3.predict(x_train)
y_test_pred_tree = model3.predict(x_test)

In [15]:
#model 3 evaluation
train_acc3 = accuracy_score(y_train, y_train_pred_tree)
test_acc3 = accuracy_score(y_test, y_test_pred_tree)
cm3 = confusion_matrix(y_test, y_test_pred_tree)
print("train_acc3: ", train_acc3)
print("test_acc3: ", test_acc3)
print(cm3)

train_acc3:  1.0
test_acc3:  0.9666666666666667
[[11  0  0]
 [ 0  7  0]
 [ 0  1 11]]


Why should we not evaluate a model only using training data?

Ans: Because only use training data will get a optimistic score since the model has already seen the samples.

What is overfitting?

Ans: Overfitting is the model has good training accuracy but poor testing accuracy.

What happens if a decision tree becomes too deep?

Ans: It will cause overfitting.

What is the difference between a model parameter and a hyperparameter?

Ans: A hyperparameter is defined by user which is used to control the model. Model parameter is the value learned from the training data.

Why do we need a test set?

Ans: To evaluate the model's prediction on new data.